export default [
  { name: 'DASHBOARD', path: '', props: true, component: () => import('pages/dashboardPage.vue'),
    meta:{ title: 'DASHBOARD' }, menu:{title: 'DASHBOARD', caption: 'Ongoing orders and attention required data at a glance', icon: 'home' } },
  { name:'home', path: 'home', component: () => import('pages/dashboardPage.vue') },
  { name:'ITEM', path:'/item', props: true, component: () => import('pages/itempage.vue'), meta:{ title: 'Items'} },
  { name: 'ORDER', path: '/order', props: true, component: () => import('pages/orderPage.vue'), meta:{ title: 'Order'} },
  { name: 'REVIEWS', path: '/reviews', props: true, component: () => import('pages/reviewPage.vue'),
    meta:{ title: 'REVIEWS'}, menu:{title: 'REVIEWS', caption: 'The reviews you made on Products, Orders and on Your Sales Executives', icon: 'comment' } },
  { name: 'REVIEWADD', path: '/review_add', props: true, component: () => import('pages/review_addPage.vue'),
    meta:{ title: 'ADD REVIEW'} },
  { name: 'ORDERHISTORY', path: '/ORDERHISTORY', props: true, component: () => import('pages/orderhistoryPage.vue'),
    meta:{ title: 'ORDERHISTORY'}, menu:{title: 'ORDERHISTORY', caption: 'Add or View all the orders and their current statuses, that you placed here', icon: 'history' } },
  { name: 'PROFILE', path: '/profile', props: true, component: () => import('pages/customer_profilePage.vue'),
    meta:{ title: 'PROFILE'}, menu:{title: 'PROFILE', caption: 'Update your address, email and login passwords..', icon: 'account_circle' } },
]
