export default [
  { name:'home', path: '', component: () => import('pages/IndexPage.vue') },
  { name:'firose', path:'/firose', component: () => import('pages/Firose.vue'), meta:{ title:'Firose Page' },
    menu: { title:'Firose',caption:'Firose Experiment Page',icon:'beach_access' } },
  { name: 'ADMINDASHBOARD', path: '/admin_dashbord', props: true, component: () => import('pages/adminDashboardPage.vue'),
    meta:{ title: 'DASHBOARD'}, menu: { title:'DASHBOARD',caption:'DASHBOARD',icon:'home' } },
  { name: 'REVIEWS', path: '/reviews', props: true, component: () => import('pages/admin_reviewPage.vue'),
    meta:{ title: 'REVIEWS'}, menu: { title:'REVIEWS',caption:'REVIEWS',icon:'comment_bank' } },
  { name: 'LEAVES', path: '/admin_leave', props: true, component: () => import('pages/admin_leavePage.vue'),
    meta:{ title: 'LEAVES'}, menu: { title:'LEAVES',caption:'LEAVES',icon:'sick' } },
  { name: 'ADMINAREA', path: '/admin_area', props: true, component: () => import('pages/admin_areaPage.vue'),
    meta:{ title: 'Area'}, menu: { title:'AREA',caption:'AREA',icon:'area_chart' } },
  { name: 'AREAADD', path: '/area_add', props: true, component: () => import('pages/area_addPage.vue'),
    meta:{ title: 'Area'} },
  { name: 'ADMINITEMS', path: '/admin_items', props: true, component: () => import('pages/admin_itemPage.vue'),
    meta:{ title: 'Items'}, menu: { title:'ITEMS',caption:'ITEMS',icon:'add_shopping_cart' } },
  { name: 'ITEMADD', path: '/item_add', props: true, component: () => import('pages/item_addPage.vue')},
  { name: 'ADMINCUSTOMERS', path: '/admin_customer', props: true, component: () => import('pages/admin_customerPage.vue'),
    meta:{ title: 'CUSTOMERS'}, menu: { title:'CUSTOMERS',caption:'CUSTOMERS',icon:'people' } },
  { name: 'CUSTOMERADD', path: '/customer_add', props: true, component: () => import('pages/customer_addPage.vue')},
  { name: 'SALES EXECUTIVE', path: '/admin_customer', props: true, component: () => import('pages/admin_customerPage.vue'),
    meta:{ title: 'SALES EXECUTIVE'}, menu: { title:'SALES EXECUTIVE',caption:'SALES EXECUTIVE',icon:'perm_contact_calendar' } },
  { name: 'ADMINORDERHISTORY', path: '/admin_orderhistory', props: true, component: () => import('pages/admin_orderhistoryPage.vue'),
    meta:{ title: 'Order History'}, menu: { title:'ORDER HISTORY',caption:'ORDER HISTORY',icon:'history' } },
  { name: 'ADMINPROFILE', path: '/admin_profile', props: true, component: () => import('pages/admin_profilePage.vue'),
    meta:{ title: 'Profile'}, menu: { title:'PROFILE',caption:'PROFILE',icon:'manage_accounts' } },
]
